# -*- coding: utf-8 -*-
from plone.registry.interfaces import IRegistry
from zope.component import getUtility
from zope.schema.vocabulary import SimpleVocabulary

dict_plan_comptable_communal = {
    "106-01": ["Notes de crédit et ristournes du service ordinaire", "R", "O"],
    "106-02": ["Récupération de charges de personnel payées indûment", "R", "O"],
    "111-01": ["Traitements du personnel communal", "D", "O"],
    "111-02": ["Traitements du personnel contractuel subsidié", "D", "O"],
    "111-08": ["Indemnités de prestations du personnel communal", "D", "O"],
    "111-09": ["Indemnités de prestations du personnel contractuel subsidié", "D", "O"],
    "111-11": ["Traitements à charge de l'aut. sup. du personnel enseignant", "D", "O"],
    "111-12": ["Traitements à charge de la commune du personnel enseignant", "D", "O"],
    "111-19": ["Indemnités de prestations du personnel enseignant", "D", "O"],
    "111-21": ["Traitements des mandataires communaux", "D", "O"],
    "111-22": ["Jetons de présence des mandataires communaux", "D", "O"],
    "112-01": ["Pécule de vacances du personnel communal", "D", "O"],
    "112-02": ["Pécule de vacances du personnel contractuel subsidié", "D", "O"],
    "112-12": [
        "Pécule de vacances à charge de la commune du personnel enseignant",
        "D",
        "O",
    ],
    "112-21": ["Indemnités de dernière maladie et de funérailles", "D", "O"],
    "112-48": ["Autres allocations et interventions sociales", "D", "O"],
    "113-01": ["Cotis. patr. à l'ONSSAPL pour le personnel communal", "D", "O"],
    "113-02": [
        "Cotis. patr. à l'ONSSAPL pour le personnel contractuel subsidié",
        "D",
        "O",
    ],
    "113-08": [
        "Cotis. patr. à l'ONSSAPL des indemnités de prestations du personnel communal",
        "D",
        "O",
    ],
    "113-09": [
        "Cotis. patr. à l'ONSSAPL des indemnités de prestations du personnel contractuel subsidié",
        "D",
        "O",
    ],
    "113-12": [
        "Cotis. patr. à l'ONSSAPL à charge de la commune pour le personnel enseignant",
        "D",
        "O",
    ],
    "113-19": [
        "Cotis. patr. à l'ONSSAPL des indemnités de prestations du personnel enseignant",
        "D",
        "O",
    ],
    "113-21": [
        "Cotis. patr. à la caisse de répartition des pensions du personnel communal",
        "D",
        "O",
    ],
    "113-22": [
        "Cotis. patr. à la caisse communale de pension du personnel communal",
        "D",
        "O",
    ],
    "113-31": [
        "Cotis. patr. à charge de la commune à la caisse de répartition des pensions du personnel enseignant",
        "D",
        "O",
    ],
    "113-32": [
        "Cotis. patr. à charge de la commune à la caisse communale de pension du personnel enseignant",
        "D",
        "O",
    ],
    "113-48": ["Cotis. patr. pour les autres caisses de pension", "D", "O"],
    "115-01": [
        "Frais de déplacements du domicile au lieu de travail du personnel communal",
        "D",
        "O",
    ],
    "115-02": [
        "Frais de déplacements du domicile au lieu de travail du personnel contractuel subsidié",
        "D",
        "O",
    ],
    "115-12": [
        "Frais de déplacements du domicile au lieu de travail du personnel enseignant",
        "D",
        "O",
    ],
    "115-21": ["Transports gratuits assurés par la commune", "D", "O"],
    "115-41": [
        "Autres interventions et avantages en numéraires pour le personnel communal",
        "D",
        "O",
    ],
    "115-42": [
        "Autres interventions et avantages en numéraires pour le personnel contractuel subsidié",
        "D",
        "O",
    ],
    "115-43": [
        "Autres interventions et avantages en numéraires pour le personnel enseignant",
        "D",
        "O",
    ],
    "116-01": ["Pensions directement à charge de la commune", "D", "O"],
    "116-02": ["Rentes directement à charge de la commune", "D", "O"],
    "117-01": [
        "Primes versées pour couvrir l'assurance contre les accidents de travail",
        "D",
        "O",
    ],
    "117-02": ["Cotisations versées au service médical du travail", "D", "O"],
    "118-01": ["Cotisations au service social collectif ou communal", "D", "O"],
    "118-02": ["Cotisations aux autres services sociaux", "D", "O"],
    "121-01": [
        "Frais de déplacements et de séjour du personnel communal et des mandataires",
        "D",
        "O",
    ],
    "121-02": ["Indemnités de logement du personnel communal", "D", "O"],
    "121-03": ["Indemnités de frais d'habillement du personnel communal", "D", "O"],
    "121-48": ["Indemnités diverses", "D", "O"],
    "122-01": ["Honoraires et indemnités pour expertises", "D", "O"],
    "122-02": [
        "Honoraires et indemnités pour études et travaux du service ordinaire",
        "D",
        "O",
    ],
    "122-03": [
        "Honoraires et indemnités pour avocats, médecins et personnel paramédical",
        "D",
        "O",
    ],

    "122-04": [
        "Droits d'auteur, honoraires et indemnités pour artistes, professeurs, orateurs et guides",
        "D",
        "O",
    ],
    "122-05": ["Jetons de présence des commissions et jurys", "D", "O"],
    "122-06": [
        "Remboursement des charges du personnel détaché dans la commune",
        "D",
        "O",
    ],
    "122-48": ["Indemnités pour autres prestations", "D", "O"],
    "123-01": ["Fournitures administratives pour gestion de stocks", "D", "O"],
    "123-02": ["Fournitures administratives pour consommation directe", "D", "O"],
    "123-03": [
        "Fournitures administratives pour gestion de stocks destinés à la revente",
        "D",
        "O",
    ],
    "123-04": ["Fournitures administratives destinées à la revente directe", "D", "O"],
    "123-06": [
        "Prestations administratives de tiers spécifiques à la fonction",
        "D",
        "O",
    ],
    "123-07": ["Frais de correspondance", "D", "O"],
    "123-11": ["Frais de téléphone", "D", "O"],
    "123-12": [
        "Frais de location et d'entretien du matériel et du mobilier de bureau",
        "D",
        "O",
    ],
    "123-13": ["Frais de gestion et du fonctionnement de l'informatique", "D", "O"],
    "123-14": ["Prestations du service médical du travail", "D", "O"],
    "123-15": ["Frais de procédure et de poursuite", "D", "O"],
    "123-16": ["Frais de réception et de représentation", "D", "O"],
    "123-17": ["Frais de formation du personnel", "D", "O"],
    "123-18": ["Frais d'organisation des examens", "D", "O"],
    "123-19": ["Frais d'achats de livres, de documentation et d'abonnements", "D", "O"],
    "123-20": ["Frais de ventes et locations spécifiques à la fonction", "D", "O"],
    "123-48": ["Autres frais administratifs", "D", "O"],
    "124-01": ["Fournitures techniques pour gestion de stocks", "D", "O"],
    "124-02": ["Fournitures techniques pour consommation directe", "D", "O"],
    "124-03": [
        "Fournitures techniques pour gestion de stocks destinées à la revente",
        "D",
        "O",
    ],
    "124-04": ["Fournitures techniques destinées à la revente directe", "D", "O"],
    "124-05": [
        "Fournitures, entretien et location des vêtements de travail pour le personnel communal",
        "D",
        "O",
    ],
    "124-06": ["Prestations techniques de tiers spécifiques à la fonction", "D", "O"],
    "124-08": ["Assurances diverses (RC, vol, incendie, mobilier, etc...)", "D", "O"],
    "124-10": [
        "Impôts, taxes et redevances divers spécifiques à la fonction",
        "D",
        "O",
    ],
    "124-12": ["Location et entretien des fournitures techniques", "D", "O"],
    "124-13": ["Fournitures d'énergie pour le fonctionnement", "D", "O"],
    "124-21": ["Fournitures pour remises de prix, de jouets, etc...", "D", "O"],
    "124-22": [
        "Frais de voyages scolaires, excursions, classes de plein air",
        "D",
        "O",
    ],
    "124-23": ["Frais d'organisation des repas scolaires", "D", "O"],
    "124-24": ["Autres avantages scolaires", "D", "O"],
    "124-48": ["Autres frais techniques", "D", "O"],
    "125-01": ["Fournitures pour les bâtiments pour gestion de stock", "D", "O"],
    "125-02": ["Fournitures pour les bâtiments pour consommation directe", "D", "O"],
    "125-03": ["Fourniture de combustibles pour le chauffage des bâtiments", "D", "O"],
    "125-06": ["Prestations de tiers pour les bâtiments", "D", "O"],
    "125-08": ["Assurances couvrant les biens immobiliers", "D", "O"],
    "125-10": ["Impôts, taxes et redevances diverses sur biens immobiliers", "D", "O"],
    "125-12": ["Fournitures d'électricité pour les bâtiments", "D", "O"],
    "125-13": ["Fournitures de gaz pour les bâtiments", "D", "O"],
    "125-14": ["Fournitures de vapeur pour les bâtiments", "D", "O"],
    "125-15": ["Fournitures d'eau pour les bâtiments", "D", "O"],
    "125-48": ["Autres frais pour les bâtiments", "D", "O"],
    "126-01": ["Loyers et charges locatives des immeubles loués", "D", "O"],
    "127-01": ["Fournitures pour les véhicules pour gestion de stock", "D", "O"],
    "127-02": [
        "Fournitures pour les véhicules de matières pour consommation directe",
        "D",
        "O",
    ],
    "127-03": ["Fournitures d'huiles et de carburant pour les véhicules", "D", "O"],
    "127-06": ["Prestations de tiers pour les véhicules", "D", "O"],
    "127-08": ["Assurances couvrant les véhicules et le charroi", "D", "O"],
    "127-10": ["Impôts et taxes sur les véhicules", "D", "O"],
    "127-12": ["Location du matériel de transport", "D", "O"],
    "127-48": ["Autres frais sur les véhicules", "D", "O"],
    "128-01": ["Frais administratifs de la gestion financière", "D", "O"],
    "128-02": ["Frais administratifs de la gestion du portefeuille", "D", "O"],
    "128-10": ["Précompte mobilier", "D", "O"],
    "129-01": ["Commission sur les emprunts publics", "D", "O"],
    "129-02": ["Commission de remboursement des emprunts publics", "D", "O"],
    "140-01": [
        "Fournitures pour la voirie et les cours d'eau pour gestion de stock",
        "D",
        "O",
    ],
    "140-02": [
        "Fournitures pour la voirie et les cours d'eau pour consommation directe",
        "D",
        "O",
    ],
    "140-06": ["Prestations de tiers pour la voirie et les cours d'eau", "D", "O"],
    "140-11": [
        "Travaux d'entretien de voirie et des cours d'eau pour le compte de tiers",
        "D",
        "O",
    ],
    "140-12": [
        "Location et entretien du matériel de voirie et des cours d'eau",
        "D",
        "O",
    ],
    "140-13": [
        "Fournitures et prestations pour la lutte contre la neige et le verglas",
        "D",
        "O",
    ],
    "140-48": [
        "Autres dépenses pour le fonctionnement de la voirie et des cours d'eau",
        "D",
        "O",
    ],
    "161-01": ["Produits de prestations directes concernant la fonction", "R", "O"],
    "161-02": ["Produits de ventes de biens concernant la fonction", "R", "O"],
    "161-03": ["Produits de la location mobilière relative à la fonction", "R", "O"],
    "161-04": ["Produits des droits d'entrée", "R", "O"],
    "161-05": ["Produits des concessions de droits accordées", "R", "O"],
    "161-06": ["Récupération des frais de procédure et de poursuite", "R", "O"],
    "161-07": ["Interventions des parents dans les transports scolaires", "R", "O"],
    "161-08": ["Interventions des parents dans les repas scolaires", "R", "O"],
    "161-09": ["Intervention des parents dans la surveillance et les cours", "R", "O"],
    "161-10": [
        "Intervention des parents dans les classes de plein air et de neige",
        "R",
        "O",
    ],
    "161-11": ["Produits des droits forestiers d'affouage et d'abattage", "R", "O"],
    "161-12": ["Produits de la vente des coupes de bois sur pied", "R", "O"],
    "161-13": ["Produits de la vente des bois abattus", "R", "O"],
    "161-14": [
        "Remboursements des avantages en nature du personnel et des mandataires",
        "R",
        "O",
    ],
    "161-48": ["Produits et récupérations divers relatifs à la fonction", "R", "O"],
    "162-01": ["Produits de prestations pour les pouvoirs publics", "R", "O"],
    "163-01": [
        "Produits des locations immobilières aux entreprises et aux ménages",
        "R",
        "O",
    ],
    "164-01": ["Produits des locations immobilières aux pouvoirs publics", "R", "O"],
    "180-01": ["Récupération des travaux exécutés pour le compte de tiers", "R", "O"],
    "180-02": ["Droits de passage", "R", "O"],
    "180-48": ["Produits des interventions diverses", "R", "O"],
    "206-01": [
        "Récupération des charges financières et des pertes des entreprises",
        "R",
        "O",
    ],
    "211-01": ["Charge financière des emprunts à charge de la commune", "D", "O"],
    "211-03": ["Charge financière de location financement", "D", "O"],
    "211-04": ["Charge financière des emprunts publics", "D", "O"],
    "211-05": ["Charge financière des emprunts d'assainissement", "D", "O"],
    "211-06": ["Charge financière des emprunts de préfinancement", "D", "O"],
    "212-01": [
        "Charge financière des emprunts à charge de l'autorité supérieure",
        "D",
        "O",
    ],
    "213-01": ["Charge financière des emprunts pour le compte de tiers", "D", "O"],
    "214-01": ["Intérêts débiteurs des comptes au crédit communal", "D", "O"],
    "214-02": [
        "Intérêts débiteurs des comptes d'escompte de subsides au crédit communal",
        "D",
        "O",
    ],
    "214-03": ["Intérêts débiteurs des comptes financiers divers", "D", "O"],
    "215-01": ["Intérêts moratoires, de retard et assimilés", "D", "O"],
    "215-02": ["Amendes et astreintes", "D", "O"],
    "216-01": ["Pertes de change", "D", "O"],
    "217-01": ["Primes d'émission des emprunts et commissions de prêts", "D", "O"],
    "218-01": [
        "Intérets débiteurs d'emprunts contractés par des tiers et garantis par la commune",
        "D",
        "O",
    ],
    "219-01": ["Rentes viagères et perpétuelles à payer", "D", "O"],
    "221-01": [
        "Participations aux pertes d'exploitation des régies communales",
        "D",
        "O",
    ],
    "222-01": [
        "Participations aux pertes d'exploitation des intercommunales",
        "D",
        "O",
    ],
    "223-01": [
        "Participations aux pertes d'exploitation des sociétés fédérales et régionales",
        "D",
        "O",
    ],
    "224-01": [
        "Participations aux pertes d'exploitation du crédit communal de Belgique",
        "D",
        "O",
    ],
    "225-01": [
        "Participations aux pertes d'exploitation des autres entreprises publiques",
        "D",
        "O",
    ],
    "227-01": ["Primes d'émission des emprunts publics", "D", "O"],
    "229-01": ["Charges relatives aux opérations de la dette publique", "D", "O"],
    "261-01": ["Intérêts créditeurs des titres de placements", "R", "O"],
    "261-03": ["Intérêts créditeurs des prêts accordés à plus d'un an", "R", "O"],
    "262-01": ["Ristournes sur intérêts des emprunts", "R", "O"],
    "263-01": [
        "Remboursements des charges financières des emprunts à charge de tiers",
        "R",
        "O",
    ],
    "264-01": [
        "Intérêts créditeurs sur les comptes courants au crédit communal",
        "R",
        "O",
    ],
    "264-02": [
        "Intérêts créditeurs sur les comptes de placements à terme au crédit communal",
        "R",
        "O",
    ],
    "264-03": ["Intérêts créditeurs de comptes financiers divers", "R", "O"],
    "264-04": [
        "Intérêts créditeurs sur les comptes de placements à terme divers",
        "R",
        "O",
    ],
    "265-01": ["Intérêts de retard créditeurs sur les créances", "R", "O"],
    "266-01": ["Bénéfices de change", "R", "O"],
    "268-01": [
        "Récupération sur tiers des charges financières d'emprunts garantis par la commune",
        "R",
        "O",
    ],
    "269-01": ["Produits des rentes viagères et perpétuelles", "R", "O"],
    "271-01": ["Participations dans les bénéfices des régies communales", "R", "O"],
    "272-01": ["Dividendes de participations dans les intercommunales", "R", "O"],
    "273-01": [
        "Dividendes de participations dans les sociétés fédérales et régionales",
        "R",
        "O",
    ],
    "274-01": ["Dividendes de participations dans le crédit communal", "R", "O"],
    "275-01": [
        "Dividendes de participations dans les autres entreprises publiques",
        "R",
        "O",
    ],
    "280-01": ["Dividendes de participations dans les entreprises privées", "R", "O"],
    "280-02": ["Dividendes et ristournes sur des concessions accordées", "R", "O"],
    "301-01": [
        "Non-valeurs de droits constatés non perçus du service ordinaire",
        "D",
        "O",
    ],
    "301-02": [
        "Remboursement de non-valeurs sur droits constatés perçus du service ordinaire",
        "D",
        "O",
    ],
    "302-01": ["Déficit de trésorerie", "D", "O"],
    "306-01": ["Récupération des transferts de revenus au secteur privé", "R", "O"],
    "307-01": ["Excédent de trésorerie", "R", "O"],
    "310-01": ["Subsides en loyers et en intérêts aux entreprises", "D", "O"],
    "321-01": ["Subsides et primes directs accordés aux entreprises", "D", "O"],
    "321-02": ["Remboursement de frais d'exploitation aux entreprises", "D", "O"],
    "322-01": ["Subsides indirects divers accordés aux entreprises", "D", "O"],
    "322-48": ["Réparation de petits dommages aux entreprises", "D", "O"],
    "331-01": ["Subsides et primes directs accordés aux ménages", "D", "O"],
    "332-01": ["Cotisations de membre des associations d'intérêt communal", "D", "O"],
    "332-02": ["Subsides aux organismes au service des ménages", "D", "O"],
    "332-03": ["Subsides aux organismes au service des ménages", "D", "O"],
    "332-48": ["Réparation de petits dommages aux ménages", "D", "O"],
    "361-01": ["Taxe sur la conservation des véhicules saisis par la police", "R", "O"],
    "361-02": [
        "Taxe sur la délivrance de documents concernant les établissements dangereux, incommodes et insalubres",
        "R",
        "O",
    ],
    "361-03": ["Taxe sur la délivrance de permis de lotir", "R", "O"],
    "361-04": ["Taxe sur la délivrance de documents administratifs", "R", "O"],
    "361-48": ["Taxe sur les prestations administratives diverses", "R", "O"],
    "362-01": ["Taxes pour l'acquisition de terrains de voirie", "R", "O"],
    "362-02": ["Taxes pour le pavage des rues", "R", "O"],
    "362-03": ["Taxe pour la construction des trottoirs", "R", "O"],
    "362-04": ["Taxe pour la construction des égouts", "R", "O"],
    "362-05": ["Taxe pour le raccordement au réseau d'égout", "R", "O"],
    "362-06": ["Taxe pour la construction de conduites d'eau", "R", "O"],
    "362-07": ["Taxe d'urbanisation", "R", "O"],
    "362-08": ["Taxe sur l'inflexion dans les trottoirs", "R", "O"],
    "362-09": ["Taxe pour commodités spéciales dans les rues piétonnières", "R", "O"],
    "362-48": ["Taxes diverses de remboursement", "R", "O"],
    "363-01": ["Taxe sur les bâtiments reliés ou reliables au réseau d'eau", "R", "O"],
    "363-02": ["Taxe sur le raccordement au réseau de distribution d'eau", "R", "O"],
    "363-03": ["Taxe sur l'enlèvement des immondices et résidus ménagers", "R", "O"],
    "363-04": ["Taxe sur la vidange des fosses d'aisance", "R", "O"],
    "363-05": ["Taxe sur l'enlèvement de déchets industriels et encombrants", "R", "O"],
    "363-06": ["Taxe d'enlèvement et d'entreposage de véhicules ou d'objets", "R", "O"],
    "363-07": [
        "Taxe sur le déversement sauvage d'immondices sur la voie publique",
        "R",
        "O",
    ],
    "363-08": [
        "Taxe sur les immeubles reliés ou reliables au réseau d'égouts",
        "R",
        "O",
    ],
    "363-09": ["Taxe sur l'entretien des égouts", "R", "O"],
    "363-10": [
        "Taxe sur les inhumations, dispersion de cendres, columbarium",
        "R",
        "O",
    ],
    "363-11": ["Taxe sur les exhumations", "R", "O"],
    "363-12": ["Taxe sur les transports funèbres", "R", "O"],
    "363-13": ["Taxe sur l'occupation des caveaux d'attente", "R", "O"],
    "363-14": ["Taxe sur le séjour à la morgue ou au dépôt mortuaire", "R", "O"],
    "363-15": ["Tace sur les tombes et caveaux", "R", "O"],
    "363-16": [
        "Taxe sur la délivrance de récipients ou d'autocollants pour les résidus ménagers",
        "R",
        "O",
    ],
    "363-17": ["Taxe pour la protection de l'environnement", "R", "O"],
    "363-18": ["Taxe pour l'utilisation de conteneurs communaux", "R", "O"],
    "363-48": ["Taxes diverses sur prestations d'hygiène publique", "R", "O"],
    "364-01": ["Taxe sur le personnel occupé", "R", "O"],
    "364-02": ["Taxe sur les serveuses de bar", "R", "O"],
    "364-03": ["Taxe sur la force motrice", "R", "O"],
    "364-04": ["Taxe sur les tanks et les réservoirs", "R", "O"],
    "364-05": ["Taxe sur les fours à coke", "R", "O"],
    "364-06": ["Taxe sur les charbonnages", "R", "O"],
    "364-07": ["Taxe sur les briqueteries", "R", "O"],
    "364-08": ["Taxe sur les brasseries", "R", "O"],
    "364-09": ["Taxe sur les carrières", "R", "O"],
    "364-10": ["Taxe sur les industries chimiques", "R", "O"],
    "364-11": ["Taxe pour le démergement", "R", "O"],
    "364-12": ["Taxe sur les débits de boissons", "R", "O"],
    "364-13": ["Taxe sur les débits de tabac", "R", "O"],
    "364-14": ["Taxe sur les salles de vente", "R", "O"],
    "364-15": ["Taxe sur le colportage", "R", "O"],
    "364-16": ["Taxe sur les agences de paris et de jeux", "R", "O"],
    "364-17": [
        "Taxe sur les débits de boissons ouverts en dehors des heures",
        "R",
        "O",
    ],
    "364-18": ["Taxe sur les cercles privés", "R", "O"],
    "364-19": ["Taxe sur les étalages et les vitrines", "R", "O"],
    "364-20": ["Taxe sur l'autorisation de vendre du poisson", "R", "O"],
    "364-21": ["Taxe sur les exploitations de taxis", "R", "O"],
    "364-22": ["Taxe sur les enseignes et réclames lumineuses", "R", "O"],
    "364-23": ["Taxe sur les panneaux publicitaires", "R", "O"],
    "364-24": ["Taxe sur la diffusion publicitaire", "R", "O"],
    "364-25": ["Taxe sur les panneaux directionnels", "R", "O"],
    "364-26": ["Taxe de séjour", "R", "O"],
    "364-27": ["Taxe sur les terrains de camping", "R", "O"],
    "364-28": ["Taxe sur les dépôts de matériaux", "R", "O"],
    "364-29": [
        "Taxe sur les dépôts de mitraille, véhicules usagés, abandonnés",
        "R",
        "O",
    ],
    "364-30": [
        "Taxe annuelle sur les établissements dangereux, insalubres ou incommodes",
        "R",
        "O",
    ],
    "364-31": [
        "Autre taxe sur les établissements dangereux, insalubres ou incommodes",
        "R",
        "O",
    ],
    "364-32": ["Taxe sur les banques et les institutions financières", "R", "O"],
    "364-33": ["Taxe sur les décharges", "R", "O"],
    "364-34": ["Taxe sur les chambres", "R", "O"],
    "364-35": ["Taxe sur les maisons de rendez-vous", "R", "O"],
    "364-48": ["Taxes diverses sur les entreprises", "R", "O"],
    "365-01": ["Taxe sur les spectacles", "R", "O"],
    "365-02": ["Taxe sur les bals publics", "R", "O"],
    "365-03": ["Taxe sur les instruments de musique et de télévision", "R", "O"],
    "365-04": ["Taxe sur le port de masques", "R", "O"],
    "365-05": ["Taxe sur les jeux de quilles", "R", "O"],
    "365-06": ["Taxe sur les appareils de jeux non automatiques", "R", "O"],
    "365-07": ["Taxe sur les jeux et paris", "R", "O"],
    "365-08": ["Taxe sur les locations de bâteaux", "R", "O"],
    "365-09": ["Taxe sur la location d'animaux de selle", "R", "O"],
    "365-10": ["Taxe sur les lunaparks", "R", "O"],
    "365-48": ["Taxes diverses sur les spectacles et divertissements", "R", "O"],
    "366-01": ["Taxe sur les droits d'emplacement sur les marchés", "R", "O"],
    "366-03": ["Taxe sur les forains, les loges foraines et mobiles", "R", "O"],
    "366-05": ["Taxe de droits de quai", "R", "O"],
    "366-06": ["Taxe sur le placement de terrasses, tables, chaises", "R", "O"],
    "366-07": ["Taxe sur les parkings", "R", "O"],
    "366-08": ["Taxe sur le stationnement des taxis et voitures de louage", "R", "O"],
    "366-09": [
        "Taxe sur les kiosques à journaux, sur les baraques à frites,...",
        "R",
        "O",
    ],
    "366-10": ["Taxe sur l'exploitation des plages et des rives", "R", "O"],
    "366-11": ["Taxe sur les photographes et filmeurs", "R", "O"],
    "366-12": ["Taxe sur les pompes à essence, à huile, à air comprimé", "R", "O"],
    "366-13": ["Taxe sur les distributeurs automatiques", "R", "O"],
    "366-14": ["Taxe sur les occupations diverses de la voie publique", "R", "O"],
    "366-15": ["Taxe sur les appareils de chargement et de déchargement", "R", "O"],
    "366-48": ["Taxes diverses sur l'occupation du domaine public", "R", "O"],
    "367-01": ["Taxe sur le patrimoine mobilier", "R", "O"],
    "367-02": [
        "Taxe sur la construction, l'aménagement de bâtiments ou de palissades",
        "R",
        "O",
    ],
    "367-03": ["Taxe sur les balcons, loggias et marquises", "R", "O"],
    "367-04": ["Taxe sur les gouttières, gargouilles, couvre-rigoles", "R", "O"],
    "367-05": ["Taxe sur les entrées de caves, soupiraux, caves sous voirie", "R", "O"],
    "367-06": ["Taxe sur les portes cochères", "R", "O"],
    "367-07": ["Taxe sur les grillages et les clôtures", "R", "O"],
    "367-08": ["Taxe sur les chalets de vacances d'agrément, caravanes", "R", "O"],
    "367-09": [
        "Taxe sur les terrains à bâtir non bâtis (loi 29.03.1962 article 70bis)",
        "R",
        "O",
    ],
    "367-10": ["Taxe sur les antennes extérieures", "R", "O"],
    "367-11": ["Taxe sur l'absence de places de parking", "R", "O"],
    "367-12": ["Taxe sur les biens exonérés du précompte immobilier", "R", "O"],
    "367-13": ["Taxe sur les secondes résidences", "R", "O"],
    "367-14": ["Taxe sur les terrains non bâtis situés dans les dunes", "R", "O"],
    "367-15": ["Taxe sur les immeubles inoccupés, inachevés, les taudis", "R", "O"],
    "367-16": ["Taxe sur les ruines industrielles", "R", "O"],
    "367-17": ["Taxe sur les bois et forêts", "R", "O"],
    "367-18": ["Taxe sur les piscines privées", "R", "O"],
    "367-19": ["Taxe sur les surfaces de bureau", "R", "O"],
    "367-20": [
        "Taxe sur les locaux destinés à l'accomplissement d'actes de commerce",
        "R",
        "O",
    ],
    "367-48": ["Taxes diverses sur le patrimoine", "R", "O"],
    "368-01": ["Taxe sur le personnel de maison et de service", "R", "O"],
    "368-02": ["Taxe sur les chevaux de luxe", "R", "O"],
    "368-03": ["Taxe sur les pigeonniers", "R", "O"],
    "368-04": ["Taxe sur les chiens", "R", "O"],
    "368-05": ["Taxe sur les permis de chasse et de port d'arme", "R", "O"],
    "368-06": ["Taxe sur la tenderie", "R", "O"],
    "368-07": ["Taxe sur les véhicules sans moteur", "R", "O"],
    "368-08": ["Taxe sur les bicyclettes et les cyclomoteurs", "R", "O"],
    "368-09": ["Taxe sur les motocyclettes, bâteaux et canots de plaisance", "R", "O"],
    "368-10": ["Taxe sur le contrôle, le plombage et le pressage de houblon", "R", "O"],
    "368-11": ["Taxe sur les stands de tir", "R", "O"],
    "368-12": ["Taxe sur les courts de tennis", "R", "O"],
    "368-13": ["Taxe sur le transpport des personnes en état d'ivresse", "R", "O"],
    "368-14": ["Taxe communale à caractère général", "R", "O"],
    "368-15": ["Taxe sur les terrains de golf", "R", "O"],
    "368-16": ["Taxe sur les lâchers de pigeon", "R", "O"],
    "368-17": ["Taxe sur les fausses alertes", "R", "O"],
    "368-48": ["Taxes diverses", "R", "O"],
    "371-01": ["Taxe additionnelle au précompte immobilier", "R", "O"],
    "372-01": ["Taxe additionnelle à l'impôt des personnes physiques", "R", "O"],
    "373-01": ["Taxe additionnelle à la taxe sur les automobiles", "R", "O"],
    "374-01": ["Taxe additionnelle à la taxe sur les vélos, vélomoteurs", "R", "O"],
    "374-02": [
        "Taxe additionnelle à la taxe sur les motos et bateaux et les canots de plaisance",
        "R",
        "O",
    ],
    "374-03": ["Taxe additionnelle à la taxe sur les véhicules sans moteur", "R", "O"],
    "375-01": ["Taxe additionnelle à la taxe sur les chiens", "R", "O"],
    "376-01": ["Taxes addtionnelles aux autres taxes provinciales", "R", "O"],
    "377-01": ["Taxes additionnelles aux taxes pour l'environnement", "R", "O"],
    "377-48": [
        "Taxes additionnelles aux autres taxes régionales ou communautaires",
        "R",
        "O",
    ],
    "380-01": [
        "Indemnités pour petits dommages des entreprises et des ménages",
        "R",
        "O",
    ],
    "380-02": ["Cotisations des mandataires pour la pension", "R", "O"],
    "380-03": ["Amendes", "R", "O"],
    "380-05": ["Dons manuels", "R", "O"],
    "380-06": [
        "Contributions des entreprises et ASBL dans les charges de traitement du personnel détaché",
        "R",
        "O",
    ],
    "380-48": ["Autres contributions des entreprises et des ménages", "R", "O"],
    "406-01": ["Récupération des ttransferts de revenus au secteur public", "R", "O"],
    "413-01": [
        "Contributions à l'autorité supérieure dans les frais de fonctionnement scolaires",
        "D",
        "O",
    ],
    "413-48": [
        "Avantages sociaux et autres avantages spécifiques à l'autorité supérieure pour l'enseignement",
        "D",
        "O",
    ],
    "415-01": [
        "Contributions à l'autorité supérieure dans les charges de traitements et de fonctionnement",
        "D",
        "O",
    ],
    "415-02": ["Intervention dans les primes syndicales", "D", "O"],
    "431-01": [
        "Contributions dans les traitements des enseignants des autres pouvoirs publics",
        "D",
        "O",
    ],
    "432-01": [
        "Contributions dans les charges de pension des enseignants des autres pouvoirs publics",
        "D",
        "O",
    ],
    "433-01": [
        "Contributions dans les autres frais de fonctionnement des autres pouvoirs publics",
        "D",
        "O",
    ],
    "434-01": [
        "Contributions dans les charges d'intérêts des autres pouvoirs publics",
        "D",
        "O",
    ],
    "435-01": [
        "Contributions dans les charges spécifiques de fonctionnement des autres pouvoirs publics",
        "D",
        "O",
    ],
    "435-02": ["Contributions dans le déficit des hôpitaux publics", "D", "O"],
    "441-01": [
        "Contributions dans les traitements des enseignants de l'enseignement libre",
        "D",
        "O",
    ],
    "442-01": [
        "Contributions dans les charges de pension des enseignants de l'enseignement libre",
        "D",
        "O",
    ],
    "443-01": ["Avantages sociaux et subsides pour l'enseignement libre", "D", "O"],
    "443-48": ["Autres avantages spécifiques aux écoles libres", "D", "O"],
    "444-01": [
        "Contributions dans les institutions de recherche scientifique avec personnalité juridique",
        "D",
        "O",
    ],
    "445-01": [
        "Contributions dans les autres institutions publiques avec personnalité juridique",
        "D",
        "O",
    ],
    "461-01": [
        "Contributions de l'autorité supérieure dans les traitements du personnel enseignant",
        "R",
        "O",
    ],
    "462-01": [
        "Contributions de l'autorité supérieure dans lescharges de pension du personnel enseignant",
        "R",
        "O",
    ],
    "463-01": [
        "Contribution de l'autorité supérieure dans les frais de fonctionnement de l'enseignement",
        "R",
        "O",
    ],
    "463-02": [
        "Contribution de l'autorité supérieure pour les fournitures classiques",
        "R",
        "O",
    ],
    "464-01": [
        "Remboursement par l'autorité supérieure des charges financières des emprunts",
        "R",
        "O",
    ],
    "465-01": [
        "Contribution de l'autorité supérieure dans les frais de fonctionnement",
        "R",
        "O",
    ],
    "465-02": [
        "Contribution de l'autorité supérieure dans les frais de personnel",
        "R",
        "O",
    ],
    "465-03": [
        "Contribution de l'autorité supérieure dans la délivrance de permis de conduire",
        "R",
        "O",
    ],
    "465-04": [
        "Contribution de l'autorité supérieure dans les frais de recensement divers",
        "R",
        "O",
    ],
    "465-05": [
        "Contribution de l'autorité supérieure pour le personnel contractuel subsidié",
        "R",
        "O",
    ],
    "465-06": [
        "Contribution de l'autorité supérieure dans les charges de traitements du personnel détaché",
        "R",
        "O",
    ],
    "465-48": ["Autres contributions spécifiques de l'autorité supérieure", "R", "O"],
    "466-01": ["Fonds des communes", "R", "O"],
    "466-02": ["Fonds complémentaire pour recettes garanties", "R", "O"],
    "466-03": ["Fonds d'aide exceptionnelle", "R", "O"],
    "466-04": ["Contributions dans les charges de pension", "R", "O"],
    "466-05": ["Aide exceptionnelle", "R", "O"],
    "466-06": [
        "Fonds spéciaux  pour les communes au centre régional d'incendie",
        "R",
        "O",
    ],
    "466-07": ["Fonds flamand pour l'intégration des plus défavorisés", "R", "O"],
    "466-08": ["Dotation particulière", "R", "O"],
    "466-09": [
        "Fonds de compensation pour la non perception des additionnels au précompte immobilier",
        "R",
        "O",
    ],
    "466-48": [
        "Autres contributions de l'autorité supérieure à des fins générales",
        "R",
        "O",
    ],
    "469-01": ["Indemnités pour petits dommages de l'autorité supérieure", "R", "O"],
    "481-01": [
        "Contributions des autres pouvoirs publics dans les traitements des enseignants",
        "R",
        "O",
    ],
    "482-01": [
        "Contributions des autres pouvoirs publics dans les pensions des enseignants",
        "R",
        "O",
    ],
    "483-01": [
        "Contribution des autres pouvoirs publics dans les frais de fonctionnement de l'enseignement",
        "R",
        "O",
    ],
    "485-01": [
        "Contribution des autres pouvoirs publics dans les frais de fonctionnement",
        "R",
        "O",
    ],
    "485-02": [
        "Contribution des autres pouvoirs publics dans les frais de personnel",
        "R",
        "O",
    ],
    "485-06": [
        "Contribution des autres pouvoirs publics dans les charges de traitement du personnel détaché",
        "R",
        "O",
    ],
    "485-48": [
        "Contributions des autres pouvoirs publics à des fins spécifiques",
        "R",
        "O",
    ],
    "489-01": ["Indemnités pour petits dommages des autres pouvoirs publics", "R", "O"],
    "490-01": ["Contributions pour les traitements de l'enseignement libre", "R", "O"],
    "510-54": [
        "Indemnité unique de droits d'emphytéose et de superficie sur des biens immobilisés appartenant aux entreprises",
        "D",
        "E",
    ],
    "512-51": ["Subsides en capital pour les investissements", "D", "E"],
    "512-52": ["Primes et contributions dans les sociétés de logement", "D", "E"],
    "512-53": ["Contributions dans les pertes des entreprises privées", "D", "E"],
    "512-54": ["Contributions aux dommages de guerre des biens immobiliers", "D", "E"],
    "512-55": ["Dédommagements extraordinaires divers", "D", "E"],
    "512-56": [
        "Cotisations uniques aux entreprises privées et primes d'assurances",
        "D",
        "E",
    ],
    "514-51": ["Garanties accordées en espèces à plus d'un an", "D", "E"],
    "520-54": [
        "Indemn. unique de droits d'emphyt. et de sup. sur biens immob. appart. aux ménages et institutions à leur service",
        "D",
        "E",
    ],
    "522-51": ["Subsides en capital aux ménages", "D", "E"],
    "522-52": ["Subsides en capital aux ASBL au service des ménages", "D", "E"],
    "522-53": ["Subsides en capital aux organismes au service des ménages", "D", "E"],
    "522-54": ["Dédommagements en responsabilité civile de la commune", "D", "E"],
    "522-55": ["Autres dédommagements accordés aux ménages", "D", "E"],
    "560-51": ["Dédommagements en capital reçus des entreprises", "R", "E"],
    "560-52": [
        "Participations en capital des entreprises pour investissements",
        "R",
        "E",
    ],
    "560-53": ["Dons et capitaux reçus des entreprises", "R", "E"],
    "560-54": [
        "Indemnité unique de droits d'emphytéose ou de superficie accordés aux entreprises",
        "R",
        "E",
    ],
    "564-51": ["Récupérations de garanties accordées à plus d'un an", "R", "E"],
    "580-51": ["Dédommagements rçus en capital des ménages", "R", "E"],
    "580-52": [
        "Capitaux reçus des ménages pour contribution aux investissements",
        "R",
        "E",
    ],
    "580-53": ["Dons et legs provenant des ménages", "R", "E"],
    "580-54": [
        "Indemn. unique de droits d'emphyt. et de sup. sur biens immob. accordés aux ménages et institut. à leur service",
        "R",
        "E",
    ],
    "606-51": ["Récupération des transferts de revenus au secteur public", "R", "E"],
    "610-54": [
        "Indemnité unique de droits d'emphytéose ou de superficie sur des biens immobilisés appartenant à l'autorité sup.",
        "D",
        "E",
    ],
    "615-51": ["Subsides d'investissement accordés à l'autorité supérieure", "D", "E"],
    "615-52": [
        "Non-valeurs de subsides d'investissement en capital de l'autorité supérieure",
        "D",
        "E",
    ],
    "630-54": [
        "Indemn. unique de droits d'emphyt. ou de superficie sur biens immob. appartenant aux autres pouvoirs publics",
        "D",
        "E",
    ],
    "631-51": [
        "Subsides en capital pour les terrains et les bâtiments scolaires aux autres pouvoirs publics",
        "D",
        "E",
    ],
    "632-51": [
        "Subsides en capital pour les équipements scolaires aux autres pouvoirs publics",
        "D",
        "E",
    ],
    "633-51": [
        "Subsides en capital pour les bâtiments aux autres pouvoirs publics",
        "D",
        "E",
    ],
    "634-51": [
        "Subsides en capital pour la voirie et les cours d'eau aux autres pouvoirs publics",
        "D",
        "E",
    ],
    "635-51": [
        "Subsides en capital à des fins spécifiques aux autres pouvoirs publics",
        "D",
        "E",
    ],
    "635-52": [
        "Non-valeurs de subsides d'investissemnt en capital des autres institutions",
        "D",
        "E",
    ],
    "641-51": ["Subsides en capital pour la construction des écoles libres", "D", "E"],
    "642-51": [
        "Subside en capital pour l'équipement de l'enseignement libre",
        "D",
        "E",
    ],
    "643-51": ["Subsides en capital pour l'enseignement scientifique", "D", "E"],
    "661-51": [
        "Subsides en capital de l'autorité supérieure pour les terrains et bâtiments scolaires",
        "R",
        "E",
    ],
    "662-51": [
        "Subsides en capital de l'autorité supérieure pour les équipements scolaires",
        "R",
        "E",
    ],
    "663-51": [
        "Subsides en capital de l'autorité supérieure pour les bâtiments",
        "R",
        "E",
    ],
    "664-01": [
        "Récupération sur l'autorité supérieure des remboursements périodiques des emprunts",
        "R",
        "O",
    ],
    "664-51": [
        "Subsides en capital de l'autorité supérieure pour travaux hydrauliques et de voirie",
        "R",
        "E",
    ],
    "665-01": ["Rermboursement d'annuités de dommages de guerre 14-18", "R", "O"],
    "665-51": ["Droits de tirage sur les fonds d'investissements", "R", "E"],
    "665-52": [
        "Subsides en capital de l'autorité supérieure pour investissements spécifiques",
        "R",
        "E",
    ],
    "667-01": [
        "Récupération sur l'autorité supérieure du remboursement des emprunts pour le déficit des hôpitaux du CPAS",
        "R",
        "O",
    ],
    "668-01": [
        "Récupération sur l'autorité supérieure du remboursement des emprunts de consolidation",
        "R",
        "O",
    ],
    "669-51": ["Dédommagements en capital de l'autorité supérieure", "R", "E"],
    "669-54": [
        "Indemnité unique de droits d'emphytéose ou de superficie de biens immobiliers accordés à l'autorité supérieure",
        "R",
        "E",
    ],
    "681-51": [
        "Subsides en capital des autres pouvoirs publics pour les terrains et bâtiments scolaires",
        "R",
        "E",
    ],
    "682-51": [
        "Subsides en capital des autres pouvoirs publics pour l'équipement scolaire",
        "R",
        "E",
    ],
    "683-51": [
        "Subsides en capital des autres pouvoirs publics pour les bâtiments",
        "R",
        "E",
    ],
    "684-51": [
        "Subsides en capital des autres pouvoirs publics pour travaux hydrauliques et de voirie",
        "R",
        "E",
    ],
    "685-51": [
        "Subsides en capital des autres pouvoirs publics à des fins spécifiques ",
        "R",
        "E",
    ],
    "689-51": ["Dédommagements en capital des autres pouvoirs publics", "R", "E"],
    "689-54": [
        "Indemnité unique de droits d'emphytéose ou de superficie de biens immob. accordés aux autres pouvoirs publics",
        "R",
        "E",
    ],
    "701-51": [
        "Non-valeurs de droits constatés non perçus du service extraordinaire",
        "D",
        "E",
    ],
    "701-52": [
        "Remboursements de non-valeurs de droits constatés perçus du service extraordinaire",
        "D",
        "E",
    ],
    "706-51": ["Note de crédit du service extraordinaire", "R", "E"],
    "711-51": ["Achats de terres agricoles", "D", "E"],
    "711-52": ["Achats de terrains à bâtir non bâtis", "D", "E"],
    "711-53": ["Achats de terrains industriels", "D", "E"],
    "711-54": [
        "Achats de terrains de parcs, de jardins, de plaines de jeux et de sports et de cimetière",
        "D",
        "E",
    ],
    "711-55": ["Achats de terrains forestiers et de réserves naturelles", "D", "E"],
    "711-56": ["Achats d'autres terrains", "D", "E"],
    "711-57": ["Achats de terrains de constructions", "D", "E"],
    "711-58": ["Achats de terrains de voirie", "D", "E"],
    "711-59": ["Achat des terrains des ouvrages d'art", "D", "E"],
    "711-60": ["Achats des terrains en cours d'exécution", "D", "E"],
    "711-61": ["Achats des terrains des cours et plans d'eau", "D", "E"],
    "711-62": ["Achats de bois sur pied", "D", "E"],
    "712-51": ["Achats de bâtiments administratifs", "D", "E"],
    "712-52": ["Achats de bâtiments scolaires", "D", "E"],
    "712-53": ["Achats de bâtiments industriels ou d'exploitation", "D", "E"],
    "712-54": ["Achats de bâtiments cultuels, culturels et sportifs", "D", "E"],
    "712-55": ["Achats de monuments ", "D", "E"],
    "712-56": ["Achats de bâtiments divers", "D", "E"],
    "712-60": ["Achats de bâtiments en cours d'exécution", "D", "E"],
    "721-51": ["Aménagements aux terrains agricoles", "D", "E"],
    "721-52": ["Aménagements aux terrains à bâtir non bâtis", "D", "E"],
    "721-53": ["Aménagements aux terrains industriels", "D", "E"],
    "721-54": [
        "Aménagements aux terrains des parcs, jardins, plaines de jeux et de sports, de cimetières",
        "D",
        "E",
    ],
    "721-55": [
        "Aménagements aux terrains forestiers, aux réserves naturelles",
        "D",
        "E",
    ],
    "721-56": ["Aménagements aux autres terrains ", "D", "E"],
    "721-57": ["Aménagements aux terrains des constructions", "D", "E"],
    "721-58": ["Plantations non amortissables sur les terrains", "D", "E"],
    "721-60": ["Aménagements aux terrains en cours d'exécution", "D", "E"],
    "721-62": ["Boisements et reboisements forestiers", "D", "E"],
    "722-51": ["Constructions de bâtiments administratifs", "D", "E"],
    "722-52": ["Constructions de bâtiments scolaires", "D", "E"],
    "722-53": ["Constructions de bâtiments industriels et d'exploitation", "D", "E"],
    "722-54": ["Constructions de bâtiments cultuels, culturels et sportifs", "D", "E"],
    "722-55": ["Constructions de monuments", "D", "E"],
    "722-56": ["Constructions de bâtiments divers", "D", "E"],
    "722-60": ["Travaux en cours d'exécution de constructions de bâtiments", "D", "E"],
    "723-51": ["Aménagements aux bâtiments administratifs", "D", "E"],
    "723-52": ["Aménagements aux bâtiments scolaires", "D", "E"],
    "723-53": ["Aménagements aux bâtiments industriels et d'exploitation", "D", "E"],
    "723-54": ["Aménagements aux bâtiments cultuels, culturels et sportifs", "D", "E"],
    "723-55": [
        "Aménagements aux bâtiments sans destination spécifique et non valorisés au bilan de départ et aux monuments",
        "D",
        "E",
    ],
    "723-56": ["Aménagements de bâtiments divers", "D", "E"],
    "723-60": ["Aménagements en cours d'exécution des bâtiments ", "D", "E"],
    "724-51": [
        "Equipement et maintenance extraordinaire des bâtiments administratifs",
        "D",
        "E",
    ],
    "724-52": [
        "Equipement et maintenance extraordinaire des bâtiments scolaires",
        "D",
        "E",
    ],
    "724-53": [
        "Equipement et maintenance extraordinaire des bâtiments industriels et d'exploitation",
        "D",
        "E",
    ],
    "724-54": [
        "Equipement et maintenance extraordinaire des bâtiments cultuels, culturels et sportifs",
        "D",
        "E",
    ],
    "724-55": [
        "Equip. et mainten. extraord. des bâtiments sans dest. spécif. et non val. au bilan de départ et des monuments",
        "D",
        "E",
    ],
    "724-56": [
        "Equipement et maintenance extraordinaire des bâtiments divers",
        "D",
        "E",
    ],
    "724-60": [
        "Equipement et maintenance en cours d'exécution des bâtiments ",
        "D",
        "E",
    ],
    "725-51": [
        "Equipement et maintenance extraordinaire des terres agricoles",
        "D",
        "E",
    ],
    "725-52": [
        "Equipement et maintenance extraordinaire des terrains à bâtir non bâtis",
        "D",
        "E",
    ],
    "725-53": [
        "Equipement et maintenance extraordinaire des terrains industriels",
        "D",
        "E",
    ],
    "725-54": [
        "Equipement et maintenance extraordinaire des parcs, jardins, plaines de jeux et de sports, cimetières",
        "D",
        "E",
    ],
    "725-55": [
        "Equipement et maintenance extraordinaire des terrains forestiers et réserves naturelles",
        "D",
        "E",
    ],
    "725-56": [
        "Equipement et maintenance extraordinaire des autres terrains",
        "D",
        "E",
    ],
    "725-57": [
        "Equipement et maintenance extraordinaire des terrains des constructions",
        "D",
        "E",
    ],
    "725-58": ["Plantations sur les terrains à amortir", "D", "E"],
    "725-60": [
        "Equipement, maintenance extraordinaire des et investissements sur les terrains en cours d'exécution",
        "D",
        "E",
    ],
    "725-62": ["Travaux d'entretien extraordinaire des bois sur pied", "D", "E"],
    "731-51": ["Terrassements et empierrements de la voirie", "D", "E"],
    "731-52": ["Revêtement de la voirie", "D", "E"],
    "731-53": ["Accessoires de la voirie", "D", "E"],
    "731-60": ["Travaux de voirie en cours d'exécution", "D", "E"],
    "732-51": ["Travaux de construction d'égouts", "D", "E"],
    "732-52": ["Travaux de construction des canalisations d'eau", "D", "E"],
    "732-53": ["Travaux de construction des autres canalisations", "D", "E"],
    "732-54": ["Travaux d'installation de l'éclairage public", "D", "E"],
    "732-55": ["Travaux de construction des cours et plans d'eau", "D", "E"],
    "732-56": [
        "Travaux de construction des ouvrages d'art (viaducs, ponts, tunnels)",
        "D",
        "E",
    ],
    "732-60": [
        "Travaux de construction d'infrastructure en cours d'exécution",
        "D",
        "E",
    ],
    "733-51": [
        "Honoraires des plans d'aménagement et d'urbanisme et d'autres études",
        "D",
        "E",
    ],
    "733-60": [
        "Honoraires des plans d'aménagement et d'urbanisme et d'autres études en cours d'exécution",
        "D",
        "E",
    ],
    "734-51": [
        "Travaux de plantations le long des voiries non amortissables",
        "D",
        "E",
    ],
    "734-60": [
        "Travaux de plantations le long des voiries en cours d'exécution",
        "D",
        "E",
    ],
    "735-51": ["Entretien extraordinaire des égouts", "D", "E"],
    "735-52": ["Entretien extraordinaire des canalisations d'eau", "D", "E"],
    "735-53": ["Entretien extraordinaire des autres canalisations", "D", "E"],
    "735-54": ["Entretien extraordinaire de l'éclairage public", "D", "E"],
    "735-55": ["Entretien extraordinaire des cours et plans d'eau", "D", "E"],
    "735-56": ["Entretien extraordinaire des ouvrages d'art", "D", "E"],
    "735-57": [
        "Entretien extraordinaire des terrassements et empierrements de voirie",
        "D",
        "E",
    ],
    "735-58": ["Travaux de plantations le long des voiries à amortir", "D", "E"],
    "735-59": ["Entretien extraordinaire des accessoires de voirie", "D", "E"],
    "735-60": [
        "Entretien extraordinaire de la voirie et de l'infrastructure en cours d'exécution",
        "D",
        "E",
    ],
    "741-51": ["Achats de mobilier de bureau", "D", "E"],
    "741-52": [
        "Achats de signalisation routière et de petits équipements de voirie",
        "D",
        "E",
    ],
    "741-98": ["Achats de mobilier divers", "D", "E"],
    "742-51": ["Achats de machines à écrire", "D", "E"],
    "742-52": ["Achats de matériel de reprographie", "D", "E"],
    "742-53": ["Achats de matériel informatique", "D", "E"],
    "742-98": ["Achats de matériel de bureau divers", "D", "E"],
    "743-51": ["Achats de vélos, vélomoteurs et motos", "D", "E"],
    "743-52": ["Achats d'autos et de camionnettes", "D", "E"],
    "743-53": ["Achats de camions", "D", "E"],
    "743-98": ["Achats de véhicules spéciaux et divers", "D", "E"],
    "744-51": [
        "Achats de machines et de matériel d'équipement et d'exploitation",
        "D",
        "E",
    ],
    "745-51": [
        "Maintenance extraordinaire du matériel d'équipement et d'exploitation en général",
        "D",
        "E",
    ],
    "745-52": ["Maintenance extraordinaire des autos et camionnettes", "D", "E"],
    "745-53": ["Maintenance extraordinaire des camions", "D", "E"],
    "745-98": ["Maintenance extraordinaire des véhicules spéciaux et divers", "D", "E"],
    "746-51": ["Achats de cheptel", "D", "E"],
    "747-51": ["Etudes d'organisation administrative et de gestion", "D", "E"],
    "747-60": [
        "Etudes d'organisation administrative et de gestion en cours d'exécution",
        "D",
        "E",
    ],
    "748-51": ["Biens immobiliers en location financement", "D", "E"],
    "748-52": ["Mobilier en location financement", "D", "E"],
    "748-53": ["Matériel de bureau en location financement", "D", "E"],
    "748-54": ["Matériel de transport en location financement", "D", "E"],
    "748-55": ["Matériel d'exploitation en location financement", "D", "E"],
    "748-56": ["Acquisition d'oeuvres d'art en location financement", "D", "E"],
    "749-51": ["Achat et restauration d'oeuvres d'art", "D", "E"],
    "749-52": ["Achats d'ouvrages de bibliothèques", "D", "E"],
    "749-98": ["Investissements mobiliers divers", "D", "E"],
    "761-51": ["Ventes de terres agricoles", "R", "E"],
    "761-52": ["Ventes de terrains à bâtir non bâtis", "R", "E"],
    "761-53": ["Ventes de terrains industriels", "R", "E"],
    "761-54": [
        "Ventes de terrains de parcs, jardins, plaines de jeux et de sports",
        "R",
        "E",
    ],
    "761-55": ["Ventes de terrains forestiers et de réserves naturelles", "R", "E"],
    "761-56": ["Ventes d'autres terrains ", "R", "E"],
    "761-57": ["Ventes de terrains de construction", "R", "E"],
    "761-58": ["Ventes de terrains de voirie", "R", "E"],
    "761-59": ["Ventes de terrains des ouvrages d'art", "R", "E"],
    "761-61": ["Ventes de terrains des cours et plans d'eau", "R", "E"],
    "761-62": ["Ventes de bois sur pied", "R", "E"],
    "762-51": ["Ventes de bâtiments administratifs", "R", "E"],
    "762-52": ["Ventes de bâtiments scolaires", "R", "E"],
    "762-53": ["Ventes de bâtiments industriels et d'exploitation", "R", "E"],
    "762-54": ["Ventes de bâtiments cultuels, culturels et sportifs", "R", "E"],
    "762-55": [
        "Ventes de bâtiments sans destination spécifique non valorisés au bilan de départ et de monuments",
        "R",
        "E",
    ],
    "762-56": ["Ventes de bâtiments divers", "R", "E"],
    "769-51": ["Ventes d'autres actifs immobilisés", "R", "E"],
    "771-51": ["Ventes de mobilier de bureau", "R", "E"],
    "771-98": ["Ventes de mobilier divers", "R", "E"],
    "772-51": ["Ventes de machines à écrire", "R", "E"],
    "772-52": ["Ventes de matériel de reprgraphie", "R", "E"],
    "772-53": ["Ventes de matériel informatique", "R", "E"],
    "772-98": ["Ventes de matériel de bureau divers", "R", "E"],
    "773-51": ["Ventes de vélos, vélomoteurs et motos", "R", "E"],
    "773-52": ["Ventes d'autos et de camionnettes", "R", "E"],
    "773-53": ["Ventes de camions", "R", "E"],
    "773-98": ["Ventes de véhicules spéciaux et divers", "R", "E"],
    "774-51": [
        "Ventes de machines et de matériel d'équipements et d'exploitation",
        "R",
        "E",
    ],
    "776-51": ["Ventes de cheptel", "R", "E"],
    "779-51": ["Ventes d'ouvrages d'art", "R", "E"],
    "779-52": ["Ventes d'ouvrages de bibliothèques", "R", "E"],
    "779-98": ["Ventes d'investissements mobiliers divers", "R", "E"],
    "811-51": ["Prêts aux entreprises publiques", "D", "E"],
    "812-51": [
        "Libération des participations dans les entreprises publiques",
        "D",
        "E",
    ],
    "815-54": ["Achats de titres à revenus fixes des entreprises publiques", "D", "E"],
    "816-51": ["Libération des participations dans les entreprises privées", "D", "E"],
    "817-51": ["Prêts aux entreprises privées", "D", "E"],
    "819-54": ["Achats de titres à revenus fixes des entreprises privées", "D", "E"],
    "820-51": ["Prêts aux ménages et aux ASBL", "D", "E"],
    "841-51": ["Prêts à l'autorité supérieure", "D", "E"],
    "841-54": ["Achats de titres à revenus fixes de l'autorité supérieure", "D", "E"],
    "843-51": ["Prêts au CPAS", "D", "E"],
    "843-52": ["Prêts aux fabriques d'église", "D", "E"],
    "843-53": ["Prêts aux autres pouvoirs publics", "D", "E"],
    "843-54": [
        "Achats de titres à revenus fixes des autres pouvoirs publics",
        "D",
        "E",
    ],
    "861-01": [
        "Remboursement périodique des prêts par les entreprises publiques",
        "R",
        "O",
    ],
    "861-51": [
        "Remboursement anticipé des prêts à échéance unique par les entreprises publiques",
        "R",
        "E",
    ],
    "862-51": [
        "Remboursement de participations par les entreprises publiques",
        "R",
        "E",
    ],
    "865-54": ["Vente de titres à revenus fixes des entreprises publiques", "R", "E"],
    "866-51": ["Remboursement de participations par les entreprises privées", "R", "E"],
    "867-01": [
        "Remboursement périodique des prêts par les entreprises privées",
        "R",
        "O",
    ],
    "867-51": [
        "Remboursement anticipé des prêts et remboursement des prêts à échéance unique par les entreprises privées",
        "R",
        "E",
    ],
    "869-54": ["Vente de titres à revenus fixes des entreprises privées", "R", "E"],
    "870-01": ["Remboursement périodique des prêts par les ménages et ASBL", "R", "O"],
    "870-51": [
        "Remboursement anticipé des prêts et remboursement des prêts à échéance unique par les ménages et ASBL",
        "R",
        "E",
    ],
    "891-01": [
        "Remboursement périodique des prêts par l'autorité supérieure",
        "R",
        "O",
    ],
    "891-51": ["Remboursement anticipé des prêts par l'autorité supérieure", "R", "E"],
    "891-54": ["Ventes de titres à revenus fixes de l'autorité supérieure", "R", "E"],
    "893-01": [
        "Remboursement périodique par les tiers des emprunts à leur charge",
        "R",
        "O",
    ],
    "893-02": [
        "Remboursement périodique par les autres pouvoirs publics des prêts accordés",
        "R",
        "O",
    ],
    "893-51": [
        "Remboursement anticipé par les tiers des emprunts et des emprunts à échéance unique à leur charge",
        "R",
        "E",
    ],
    "893-52": [
        "Remb. anticipé par les autres pouvoirs publics des emprunts et des emprunts à échéance unique à leur charge",
        "R",
        "E",
    ],
    "893-54": [
        "Ventes de titres à revenus fixes des autres pouvoirs publics",
        "R",
        "E",
    ],
    "911-01": [
        "Remboursement périodique des emprunts à charge de la commune",
        "D",
        "O",
    ],
    "911-03": ["Remboursement périodique des locations financements", "D", "O"],
    "911-04": ["Remboursement périodique des emprunts publics", "D", "O"],
    "911-05": [
        "Remboursement périodique des emprunts d'assainissement et de consolidation",
        "D",
        "O",
    ],
    "911-06": ["Remboursement périodique des emprunts de préfinancement", "D", "O"],
    "911-51": [
        "Remboursement anticipé d'emprunts et des emprunts à échéance unique à charge de la commune",
        "D",
        "E",
    ],
    "911-52": ["Non-valeurs des emprunts à charge de la commune", "D", "E"],
    "911-53": ["Remboursement anticipé des emprunts en location-financement", "D", "E"],
    "911-54": ["Remboursement anticipé des emprunts publics", "D", "E"],
    "911-55": [
        "Remboursement anticipé des emprunts d'assainissement et de consolidation",
        "D",
        "E",
    ],
    "911-56": [
        "Remb. antic. des emprunts de préfinancement et des empr. de préfin. à échéance unique à charge de la commune",
        "D",
        "E",
    ],
    "911-57": ["Non-valeurs des emprunts de location financement", "D", "E"],
    "912-01": [
        "Remboursement périodique des emprunts à charge de l'autorité supérieure",
        "D",
        "O",
    ],
    "912-51": [
        "Remboursement anticipé des emprunts à charge de l'autorité supérieure",
        "D",
        "E",
    ],
    "912-52": ["Non-valeurs des emprunts à charge de l'autorité supérieure", "D", "E"],
    "913-01": ["Remboursement périodique des emprunts à charge de tiers", "D", "O"],
    "913-51": [
        "Remboursement anticipé d'emprunts tiers et des emprunts tiers à échéance unique à leur charge",
        "D",
        "E",
    ],
    "913-52": ["Non-valeurs des emprunts à charge de tiers", "D", "E"],
    "918-01": [
        "Remboursement des emprunts contractés par des tiers et garantis par la commune",
        "D",
        "O",
    ],
    "951-01": ["Boni du service ordinaire", "R", "O"],
    "952-51": ["Boni du service extraordinaire", "R", "E"],
    "954-01": ["Prélèvement pour le fonds de réserves ordinaires", "D", "O"],
    "955-01": ["Prélèvement pour le fonds de réserves extraordinaires", "D", "O"],
    "955-51": ["Prélèvement pour le fonds de réserves extraordinaires", "D", "E"],
    "956-51": ["Prélèvements du service extraordinaire pour l'ordinaire", "D", "E"],
    "957-01": ["Prélèvements du service ordinaire pour l'extraordinaire", "D", "O"],
    "958-01": [
        "Prélèvements du service ordinaire pour les provisions pour risques et charges",
        "D",
        "O",
    ],
    "961-51": ["Emprunts à charge de la commune", "R", "E"],
    "961-52": ["Emprunts de location financement", "R", "E"],
    "961-54": ["Emprunts publics", "R", "E"],
    "961-55": ["Emprunts d'assainissement et de consolidation", "R", "E"],
    "961-56": ["Emprunts de préfinancement", "R", "E"],
    "962-51": ["Emprunts à charge de l'autorité supérieure", "R", "E"],
    "963-51": ["Emprunts à charge de tiers", "R", "E"],
    "968-01": ["Remboursement par les tiers des emprunts garantis", "R", "O"],
    "991-01": ["Mali du service ordinaire", "D", "O"],
    "992-51": ["Mali du service extraordinaire", "D", "E"],
    "994-01": ["Prélèvements sur le fonds de réserves ordinaires", "R", "O"],
    "995-51": ["Prélèvements sur le fonds de réserves extraordinaires", "R", "E"],
    "996-01": ["Prélèvements du service extraordinaire pour l'ordinaire", "R", "O"],
    "997-51": ["Prélèvements du service ordinaire pour l'extraordinaire", "R", "E"],
    "998-01": ["Utilisation des provisions pour risques et charges", "R", "O"],
    "998-02": ["Reprises des provisions pour risques et charges", "R", "O"],
}


def dict_list_2_vocabulary(dict_list):
    """dict_list_2_vocabulary
    Converts a dictionary list to a SimpleVocabulary

    :param dict_list: dictionary list
    """
    terms = []
    for item in dict_list:
        for key in sorted([k for k in item]):
            terms.append(SimpleVocabulary.createTerm(key, str(key), item[key]))
    return SimpleVocabulary(terms)


class PlanComptableCommunalVocabularyFactory(object):

    def __call__(self, context):
        value = []
        for pcc in sorted([k for k in dict_plan_comptable_communal]):
            txt = "{0}: {1}".format(pcc, dict_plan_comptable_communal[pcc][0])
            dict_pcc = {pcc: txt}
            value.append(dict_pcc)
        return dict_list_2_vocabulary(value)


PlanComptableCommunalVocabulary = PlanComptableCommunalVocabularyFactory()


class LastingObjectiveVocabularyFactory(object):

    def __call__(self, context):
        registry = getUtility(IRegistry)
        key_labels = sorted(registry.get('imio.project.core.lasting_objectives', {}).items())
        terms = [{key: labels['title']} for key, labels in key_labels]
        return dict_list_2_vocabulary(terms)


LastingObjectiveVocabulary = LastingObjectiveVocabularyFactory()
